### ISSUE TITLE
Documentation: instruct users to install LiberTEM ?!

### ISSUE THREAD

**Issue by w-markus** [Ptychography-4-0/ptychography#46]
When following the SSB example in [ssb.html](https://ptychography-4-0.github.io/ptychography/algorithms/ssb.html) , of course, libertem is imported.

However, it is not mentioned in the installation. 
I may take care of this, but not sure where/how to add this:

- in the current _Installation_-text of Ptychography-4-0, 
- as a separate page 
- just a sentence and a link pointing to the LiberTEM repository

Best wishes
Markus

**Comment by uellue** [comment]
Normally, LiberTEM should be installed automatically since it is a dependency of the ptychography40 package: https://github.com/Ptychography-4-0/ptychography/blob/f64e89a9cfba1016693c83fdc79e03230a9dbcb5/setup.py#L86

Was it missing on your system when you installed `ptychography40`?

**Comment by w-markus** [comment]
Yes, it was.

However, while progressing through the SSB example, I have issues since
I am running python3.9 instead of 3.7 (I assume).
I am currently downgrading debian "testing" back to "stable". Than I
will give it another try.

Am Montag, dem 26.04.2021 um 04:42 -0700 schrieb Dieter Weber:

**Comment by sk1p** [comment]
> [...] I have issues since I am running python3.9 instead of 3.7 (I assume). I am currently downgrading debian "testing" back to "stable". Than I will give it another try. 

Yes, Python 3.9 support is discussed in this issue: https://github.com/LiberTEM/LiberTEM/issues/914 which is believed to be an upstream issue in CPython, see discussion here: https://github.com/dask/distributed/issues/4168

For Debian, I would strongly suggest to use miniconda to create isolated virtual environments - then you are independent of the system Python interpreter. The problem is you can only install one version of system Python 3 at a time, so once testing or unstable updates the Python version, you have a problem. Sometimes, even minor upgrades break virtual environments. This doesn't happen with conda-created venvs. Downgrading to Debian stable could be painful, as I don't think that is officially supported.

**Comment by w-markus** [comment]
Ok. Downgrading is painful! However, I could manage to get back to Debian current "testing" distribution, aka bullseye.

I followed the above suggestion and installed miniconda and created a python-3.7 based environment there.

Now,  imports are working fine, except for hyperspy requesting more recent packages. I obeyed this by installing hyperspy explicitly to pull the required package versions.

Libertem was installed automatically. The issue remains, but for this the current title is wrong. Will open a new issue and close this one here.
